repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0 # or the latest stable version
    hooks:
      - id: black
        language_version: python3 # or specify a version like python3.9

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.4
    hooks:
      - id: pylint
        language: python
